Regression es un tipo de algoritmo de machine learning que se usa para predecir una categoria.

- Neural network regression
- Decision tree regression
- LASSO regression
- Ridge regression
- ElasticNet regression

In [1]:
import pandas as pd
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()

In [2]:
data= pd.DataFrame(iris.data)
data.columns=iris.feature_names
data['target']=iris.target
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
data['target_name'] = data['target'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

In [5]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target target_name  
0       0      setosa  
1       0      setosa  
2       0      setosa  
3       0      setosa  
4       0      setosa

In [6]:
from sklearn.model_selection import train_test_split

In [9]:
target = ['target', 'target_name']
features = list(set(list(data.columns))- set(target))
features

['sepal width (cm)',
 'sepal length (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
X = data[features].values
y = data['target'].values

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=31)

In [12]:
from sklearn.tree import DecisionTreeRegressor

In [13]:
regressor = DecisionTreeRegressor(max_depth=4)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=4)

In [14]:
predict_train = regressor.predict(X_train)
predict_test = regressor.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix

In [16]:
print(classification_report(y_test, predict_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.89      0.94        18
           2       0.88      1.00      0.93        14

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



In [17]:
#  Numeros diferentes a 0 en la transversal indica miss-classification
print(confusion_matrix(y_test, predict_test))

[[13  0  0]
 [ 0 16  2]
 [ 0  0 14]]
